### PR TITLE
⚡ Change buffer size

### PR DESCRIPTION
**Pull request by AkinoKaede**
"High Performance"

### CODE REVIEW

**Comment by moodyhunter** [comment]
I'm not familiar with the protocol internals. However, a failed test indicates that there must be something wrong.

**Comment by database64128** [comment]
outline-ss-server seems to use an even bigger buffer size

https://github.com/Jigsaw-Code/outline-ss-server/blob/77b265e5ecff580942a5a8ef6d651acd030f2aa5/shadowsocks/stream.go#L28-L33

**Comment by database64128** [comment]
@AkinoKaede I think we can go with clash's default.

**Comment by database64128** [comment]
Done in a87b0d2

**Pull request closed without merging**
